/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("uk.co.kleindelao.demo.wicket.springboot.kotlin.kotlin-application-conventions")
}

dependencies {
    implementation("com.giffing.wicket.spring.boot.starter:wicket-spring-boot-starter")
}

application {
    // Define the main class for the application.
    mainClass.set("uk.co.kleindelao.demo.wicket.springboot.label.4_3_Label.AppKt")
}
